spring:
  application:
    name: turbine
server:
  port: 8989
management:
  port: 8990
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-1:1111/eureka
turbine:
  app-config: RIBBON-CONSUME
  cluster-name-expression: "default"
  combine-host-port: true