spring:
  application:
    name: eureka-server
server:
  port: 1112
eureka:
  instance:
    hostname: eureka-server-2
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 60
  client:
    service-url:
      defaultZone: http://eureka-server-1:1111/eureka/
