spring:
  application:
    name: eureka-server
server:
  port: 1111
eureka:
  instance:
    hostname: eureka-server-1
  client:
    service-url:
      defaultZone: http://eureka-server-2:1112/eureka/
    registry-fetch-interval-seconds: 30
    fetch-registry: true