spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Arshle/Cloud.git
          search-paths: config-center/
          username: Arshle
          password: xxxxxxxxxx
          basedir: D:\configServer
        health:
          repositories:
            check:
              name: health-check
              label: master
              profiles: default
server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-1:1111/eureka/